---
name: security
on:
  pull_request

jobs:
  sast:
    runs-on: ubuntu-latest
    steps:
      - name: clone repo
        uses: actions/checkout@v3
      - name: analyse
        uses: docker://returntocorp/semgrep
        with:
          args: semgrep scan --metrics=off --config=semgrep/ ./
        env:
          SEMGREP_BASELINE_REF: 6533e025e476a9b8a20021e063912215da7ca875