---
name: security
on:
  pull_request

jobs:
  sast:
    runs-on: ubuntu-latest
    container:
      image: returntocorp/semgrep
    steps:
      - name: clone repo
        uses: actions/checkout@v3
      - name: get info
        run: ls -la ./
      - name: marked git repo as safe
        run: git config --global --add safe.directory $(pwd)
      - name: analyse
        run: semgrep scan --debug --error --metrics=off --baseline-commit ${{ github.event.pull_request.base.sha }} --config=semgrep/ ./