---
name: security
on:
  pull_request

jobs:
  sast:
    runs-on: ubuntu-latest
    container:
      image: returntocorp/semgrep
    steps:
      - name: clone repo
        uses: actions/checkout@v3
      - name: analyse
        run: semgrep scan --metrics=off --config=semgrep/ ./