---
name: security
on:
  pull_request

jobs:
  sast:
    runs-on: ubuntu-latest
    container:
      image: returntocorp/semgrep
    steps:
      - name: clone repo
        uses: actions/checkout@v3
      - name: analyse
        run: semgrep scan --error --metrics=off --config=semgrep/ ./
        env:
          SEMGREP_BASELINE_REF: ${{ github.event.pull_request.base.sha }}